export const SECURITY = {
  id: 'sec',
  title: 'Security Fundamentals',
  items: [
    { q:'SSH uses which port?', options:['22','23','443','80'], answer:0, explanation:'SSH uses TCP port 22 for encrypted remote access.' },
    { q:'Enable SSH only on VTY lines?', options:['transport input ssh','ssh enable','line vty ssh only','set vty ssh'], answer:0, explanation:'`transport input ssh` restricts access to SSH.' },
    { q:'Command to encrypt plaintext passwords?', options:['service password-encryption','enable secret','crypto password','password secure'], answer:0, explanation:'Encrypts all clear-text passwords in configuration.' },
    { q:'Strongest privileged password option?', options:['enable secret','enable password','service password-encryption','console password'], answer:0, explanation:'Enable secret uses MD5 hash and is preferred.' },
    { q:'AAA stands for?', options:['Authentication, Authorization, Accounting','Access, Authority, Authentication','Authentication and Access','Auditing Authorization Access'], answer:0, explanation:'AAA manages identity, permissions, and logging.' },
    { q:'Command to create local user?', options:['username admin password cisco','add user admin','set login admin','create user admin'], answer:0, explanation:'`username <name> password <pwd>` creates local user.' },
    { q:'Secure file transfer method?', options:['TFTP','FTP','SCP','HTTP'], answer:2, explanation:'SCP uses SSH for secure file transfer.' },
    { q:'ACL to permit 192.168.1.0/24?', options:['permit ip 192.168.1.0 0.0.0.255 any','permit 192.168.1.0/24 any','allow ip 192.168.1.0 any','access allow 192.168.1.0'], answer:0, explanation:'Wildcard mask required in ACLs.' },
    { q:'Implicit rule at end of ACL?', options:['Permit all','Deny all','Log all','None'], answer:1, explanation:'Implicit “deny all” rule at the end of every ACL.' },
    { q:'Command to apply ACL inbound?', options:['ip access-group 10 in','access-list 10 in','ip access apply 10','ip filter in'], answer:0, explanation:'Use `ip access-group 10 in` under the interface.' },
    { q:'Purpose of a firewall?', options:['Filter traffic','Assign IPs','Encrypt passwords','Manage VLANs'], answer:0, explanation:'Firewall filters traffic based on rules.' },
    { q:'Layer inspected by packet filter firewall?', options:['3 and 4','5 and 6','1 and 2','7'], answer:0, explanation:'Packet filters inspect IP and port information.' },
    { q:'IPsec mode encrypting only payload?', options:['Tunnel','Transport','Split','Proxy'], answer:1, explanation:'Transport mode encrypts only the payload.' },
    { q:'VPN stands for?', options:['Virtual Private Network','Verified Protected Network','Virtual Personal Node','Verified Port Network'], answer:0, explanation:'VPNs encrypt traffic over untrusted networks.' },
    { q:'SNMP version with auth+encryption?', options:['v1','v2c','v3','v4'], answer:2, explanation:'SNMPv3 includes security features.' },
    { q:'BPDU Guard purpose?', options:['Protect PortFast ports','Speed convergence','Block VLANs','Reset spanning tree'], answer:0, explanation:'Disables ports that receive BPDUs unexpectedly.' },
    { q:'Command to enable HTTPS server?', options:['ip http secure-server','enable https','service https','http server ssl'], answer:0, explanation:'Enables HTTPS management access.' },
    { q:'Default Telnet port?', options:['22','23','80','110'], answer:1, explanation:'Telnet uses TCP port 23 and is unsecure.' },
    { q:'Feature to limit MAC addresses on port?', options:['Port Security','DHCP Snooping','BPDU Guard','STP'], answer:0, explanation:'Port security limits learned MAC addresses.' },
    { q:'Command to disable unused ports?', options:['shutdown','disable','no enable','admin down'], answer:0, explanation:'Shutdown administratively disables port.' },
    { q:'Private VLAN purpose?', options:['Isolate devices in same VLAN','Create trunk link','Increase bandwidth','Reduce collision domains'], answer:0, explanation:'Private VLANs isolate ports within same VLAN.' },
    { q:'DHCP Snooping prevents...', options:['Rogue DHCP servers','ARP spoofing','Loops','Telnet'], answer:0, explanation:'It allows only trusted DHCP responses.' },
    { q:'Dynamic ARP Inspection prevents...', options:['Spoofing','DHCP floods','DNS leaks','VLAN hopping'], answer:0, explanation:'DAI validates ARP messages against known bindings.' },
    { q:'Enable SSH v2?', options:['ip ssh version 2','ssh enable 2','enable ssh','ssh v2 on'], answer:0, explanation:'Use `ip ssh version 2` command.' },
    { q:'HTTPS uses which protocol?', options:['SSL/TLS','SSH','IPsec','MD5'], answer:0, explanation:'HTTPS uses TLS for encryption.' },
    { q:'ACL best placed (standard)?', options:['Near destination','Near source','On gateway','Anywhere'], answer:0, explanation:'Standard ACLs near destination, extended near source.' },
    { q:'Port Security violation modes?', options:['Protect, Restrict, Shutdown','Drop, Alert, Deny','Log, Shutdown, Reset','Protect only'], answer:0, explanation:'Three modes control violation behavior.' },
    { q:'AAA server protocol?', options:['RADIUS','DNS','DHCP','NTP'], answer:0, explanation:'RADIUS is a common AAA protocol.' },
    { q:'Command to verify SSH configuration?', options:['show ip ssh','show ssh','debug ssh','show ssh version'], answer:0, explanation:'Displays SSH settings and version.' },
    { q:'DMZ purpose?', options:['Host public servers securely','Block all traffic','Encrypt VLANs','Disable routing'], answer:0, explanation:'A DMZ isolates public-facing servers from internal networks.' },
    { q:'Which command shows active ACL hits?', options:['show access-lists','show ip acl count','show ip filter','show security stats'], answer:0, explanation:'`show access-lists` displays hit counters.' },
    { q:'Which AAA method provides separate authentication and authorization?', options:['TACACS+','RADIUS','PAP','CHAP'], answer:0, explanation:'TACACS+ separates AAA functions and uses TCP port 49.' },
    { q:'SSH version 2 advantage?', options:['Improved security and encryption','Faster speed','Telnet compatibility','Uses UDP'], answer:0, explanation:'SSHv2 supports modern ciphers and improved negotiation.' },
    { q:'Purpose of a banner motd?', options:['Display legal warning','Configure hostname','Enable AAA','Encrypt data'], answer:0, explanation:'Message of the Day banners display login notices or warnings.' },
    { q:'Which command logs all CLI commands?', options:['archive log config','logging commands','terminal monitor','enable logs'], answer:0, explanation:'`archive log config` stores command history in buffer or syslog.' },
    { q:'IPsec protocol providing encryption?', options:['ESP','AH','GRE','NAT-T'], answer:0, explanation:'ESP (Encapsulating Security Payload) encrypts data.' },
    { q:'Command to generate crypto key for SSH?', options:['crypto key generate rsa','ip ssh keygen','ssh create key','crypto rsa enable'], answer:0, explanation:'Generates RSA keypair required for SSH.' },
    { q:'Purpose of access-class on VTY lines?', options:['Limit remote access by IP','Assign VLANs','Encrypt traffic','Disable STP'], answer:0, explanation:'Restricts management access by IP ACL.' },
    { q:'Which security measure mitigates VLAN hopping?', options:['Disable DTP & use native VLAN other than 1','Use PortFast','Enable CDP','Enable VTP'], answer:0, explanation:'Disable auto trunking and change native VLAN to prevent hopping.' },
    { q:'Command to verify port security?', options:['show port-security','show mac address-table secure','show interface security','show vlan secure'], answer:0, explanation:'Displays violations, allowed MACs, and status.' },
    { q:'Enable logging to syslog server?', options:['logging <server_ip>','syslog enable','enable logging','set syslog'], answer:0, explanation:'Configures destination for logs.' },
    { q:'Which protocol encrypts management traffic?', options:['SSH','Telnet','HTTP','SNMPv1'], answer:0, explanation:'SSH is encrypted, Telnet is not.' },
    { q:'How to secure unused switch ports?', options:['Shutdown ports','Set to unused VLAN','Enable Port Security','All of the above'], answer:3, explanation:'All methods are part of switch hardening best practices.' },
    { q:'What type of ACL filters based on IP and port?', options:['Extended ACL','Standard ACL','Named ACL','Wildcard ACL'], answer:0, explanation:'Extended ACLs can filter by IP and TCP/UDP port.' },
    { q:'VPN technology securing site-to-site tunnels?', options:['IPsec','GRE','VTP','STP'], answer:0, explanation:'IPsec encrypts data for site-to-site VPNs.' },
    { q:'Best practice for password security?', options:['Use complex and encrypted passwords','Use same password for all devices','Store in plaintext','Use defaults'], answer:0, explanation:'Complex, unique, and encrypted credentials improve security.' },
    { q:'DHCP snooping table stores?', options:['MAC, IP, Interface, VLAN','IP, DNS, VLAN','Username, MAC','Ports only'], answer:0, explanation:'Used by DAI to validate ARP packets.' },
    { q:'Command to restrict console login?', options:['login local','console secure','set auth console','enable password only'], answer:0, explanation:'Uses locally defined username/password pairs.' },
    { q:'Which command disables Telnet on VTY?', options:['transport input ssh','no login','no telnet','disable telnet'], answer:0, explanation:'Restricts remote login to SSH only.' },
    { q:'Port Security command to limit MAC addresses?', options:['switchport port-security maximum 2','mac-limit 2','limit mac 2','secure mac 2'], answer:0, explanation:'Limits number of allowed MAC addresses per port.' },
    { q:'Role of “enable secret”?', options:['Encrypt privileged password','Enable SSH','Login banner','Backup config'], answer:0, explanation:'Provides encrypted password for privileged EXEC access.' },
    { q:'Which SNMP version supports message encryption?', options:['v1','v2c','v3','v4'], answer:2, explanation:'SNMPv3 includes authentication and encryption.' },
    { q:'What type of attack floods MAC tables?', options:['CAM table overflow','DHCP starvation','ARP poisoning','DNS hijacking'], answer:0, explanation:'Overflows switch MAC table causing broadcast floods.' },
    { q:'Which security feature maps MAC to IP?', options:['IP Source Guard','ACL','DHCP Snooping','STP'], answer:0, explanation:'IPSG ties IP to MAC and port for validation.' },
    { q:'Port Security violation “restrict” does what?', options:['Drops packets and logs','Disables port','Shuts down interface','Allows traffic'], answer:0, explanation:'Drops traffic and increments violation counter.' },
    { q:'802.1X provides?', options:['Port-based authentication','QoS tagging','MAC filtering','VLAN pruning'], answer:0, explanation:'802.1X authenticates users via RADIUS before port activation.' },
    { q:'Command to show SSH sessions?', options:['show ssh','show session','show vty','show ssh users'], answer:0, explanation:'Displays active SSH sessions.' },
    { q:'Which protocol encrypts email traffic?', options:['SMTPS','FTP','HTTP','SNMP'], answer:0, explanation:'SMTPS uses TLS on port 465.' },
    { q:'Best practice for remote management?', options:['Use SSH and disable Telnet','Use Telnet','Use SNMPv1','Use HTTP'], answer:0, explanation:'Always use encrypted management protocols.' }
  ]
};
