export const SECURITY = {
  id: 'sec',
  title: 'Security Fundamentals',
  items: [
    { q:'SSH uses which port?', options:['22','23','443','80'], answer:0, explanation:'SSH uses TCP port 22 for encrypted remote access.' },
    { q:'Enable SSH only on VTY lines?', options:['transport input ssh','ssh enable','line vty ssh only','set vty ssh'], answer:0, explanation:'`transport input ssh` restricts access to SSH.' },
    { q:'Command to encrypt plaintext passwords?', options:['service password-encryption','enable secret','crypto password','password secure'], answer:0, explanation:'Encrypts all clear-text passwords in configuration.' },
    { q:'Strongest privileged password option?', options:['enable secret','enable password','service password-encryption','console password'], answer:0, explanation:'Enable secret uses MD5 hash and is preferred.' },
    { q:'AAA stands for?', options:['Authentication, Authorization, Accounting','Access, Authority, Authentication','Authentication and Access','Auditing Authorization Access'], answer:0, explanation:'AAA manages identity, permissions, and logging.' },
    { q:'Command to create local user?', options:['username admin password cisco','add user admin','set login admin','create user admin'], answer:0, explanation:'`username <name> password <pwd>` creates local user.' },
    { q:'Secure file transfer method?', options:['TFTP','FTP','SCP','HTTP'], answer:2, explanation:'SCP uses SSH for secure file transfer.' },
    { q:'ACL to permit 192.168.1.0/24?', options:['permit ip 192.168.1.0 0.0.0.255 any','permit 192.168.1.0/24 any','allow ip 192.168.1.0 any','access allow 192.168.1.0'], answer:0, explanation:'Wildcard mask required in ACLs.' },
    { q:'Implicit rule at end of ACL?', options:['Permit all','Deny all','Log all','None'], answer:1, explanation:'Implicit “deny all” rule at the end of every ACL.' },
    { q:'Command to apply ACL inbound?', options:['ip access-group 10 in','access-list 10 in','ip access apply 10','ip filter in'], answer:0, explanation:'Use `ip access-group 10 in` under the interface.' },
    { q:'Purpose of a firewall?', options:['Filter traffic','Assign IPs','Encrypt passwords','Manage VLANs'], answer:0, explanation:'Firewall filters traffic based on rules.' },
    { q:'Layer inspected by packet filter firewall?', options:['3 and 4','5 and 6','1 and 2','7'], answer:0, explanation:'Packet filters inspect IP and port information.' },
    { q:'IPsec mode encrypting only payload?', options:['Tunnel','Transport','Split','Proxy'], answer:1, explanation:'Transport mode encrypts only the payload.' },
    { q:'VPN stands for?', options:['Virtual Private Network','Verified Protected Network','Virtual Personal Node','Verified Port Network'], answer:0, explanation:'VPNs encrypt traffic over untrusted networks.' },
    { q:'SNMP version with auth+encryption?', options:['v1','v2c','v3','v4'], answer:2, explanation:'SNMPv3 includes security features.' },
    { q:'BPDU Guard purpose?', options:['Protect PortFast ports','Speed convergence','Block VLANs','Reset spanning tree'], answer:0, explanation:'Disables ports that receive BPDUs unexpectedly.' },
    { q:'Command to enable HTTPS server?', options:['ip http secure-server','enable https','service https','http server ssl'], answer:0, explanation:'Enables HTTPS management access.' },
    { q:'Default Telnet port?', options:['22','23','80','110'], answer:1, explanation:'Telnet uses TCP port 23 and is unsecure.' },
    { q:'Feature to limit MAC addresses on port?', options:['Port Security','DHCP Snooping','BPDU Guard','STP'], answer:0, explanation:'Port security limits learned MAC addresses.' },
    { q:'Command to disable unused ports?', options:['shutdown','disable','no enable','admin down'], answer:0, explanation:'Shutdown administratively disables port.' },
    { q:'Private VLAN purpose?', options:['Isolate devices in same VLAN','Create trunk link','Increase bandwidth','Reduce collision domains'], answer:0, explanation:'Private VLANs isolate ports within same VLAN.' },
    { q:'DHCP Snooping prevents...', options:['Rogue DHCP servers','ARP spoofing','Loops','Telnet'], answer:0, explanation:'It allows only trusted DHCP responses.' },
    { q:'Dynamic ARP Inspection prevents...', options:['Spoofing','DHCP floods','DNS leaks','VLAN hopping'], answer:0, explanation:'DAI validates ARP messages against known bindings.' },
    { q:'Enable SSH v2?', options:['ip ssh version 2','ssh enable 2','enable ssh','ssh v2 on'], answer:0, explanation:'Use `ip ssh version 2` command.' },
    { q:'HTTPS uses which protocol?', options:['SSL/TLS','SSH','IPsec','MD5'], answer:0, explanation:'HTTPS uses TLS for encryption.' },
    { q:'ACL best placed (standard)?', options:['Near destination','Near source','On gateway','Anywhere'], answer:0, explanation:'Standard ACLs near destination, extended near source.' },
    { q:'Port Security violation modes?', options:['Protect, Restrict, Shutdown','Drop, Alert, Deny','Log, Shutdown, Reset','Protect only'], answer:0, explanation:'Three modes control violation behavior.' },
    { q:'AAA server protocol?', options:['RADIUS','DNS','DHCP','NTP'], answer:0, explanation:'RADIUS is a common AAA protocol.' },
    { q:'Command to verify SSH configuration?', options:['show ip ssh','show ssh','debug ssh','show ssh version'], answer:0, explanation:'Displays SSH settings and version.' },
    { q:'DMZ purpose?', options:['Host public servers securely','Block all traffic','Encrypt VLANs','Disable routing'], answer:0
